--liquibase formatted sql

--changeset recipe-nutrition:001-schema
create table app_user (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    email varchar(255) not null unique,
    role varchar(20) not null,
    active boolean not null default true,
    created_at timestamp with time zone not null default current_timestamp
);

create table ingredient (
    id bigint generated by default as identity primary key,
    name varchar(160) not null unique,
    calories_per_unit decimal(10,2) not null,
    unit varchar(40) not null,
    created_at timestamp with time zone not null default current_timestamp
);

create table ingredient_alternative (
    ingredient_id bigint not null references ingredient(id) on delete cascade,
    alternative_id bigint not null references ingredient(id) on delete cascade,
    primary key (ingredient_id, alternative_id)
);

create table recipe (
    id bigint generated by default as identity primary key,
    name varchar(180) not null,
    image_url varchar(1000),
    status varchar(20) not null,
    author_id bigint not null references app_user(id),
    created_at timestamp with time zone not null default current_timestamp
);

create table recipe_ingredient (
    recipe_id bigint not null references recipe(id) on delete cascade,
    ingredient_id bigint not null references ingredient(id),
    quantity decimal(10,2) not null,
    position integer not null,
    primary key (recipe_id, ingredient_id)
);

create table cooking_log (
    id bigint generated by default as identity primary key,
    recipe_id bigint not null references recipe(id) on delete cascade,
    user_id bigint not null references app_user(id),
    note varchar(2000) not null,
    cooked_at timestamp with time zone not null default current_timestamp
);

create table rating (
    recipe_id bigint not null references recipe(id) on delete cascade,
    user_id bigint not null references app_user(id) on delete cascade,
    rating integer not null,
    primary key (recipe_id, user_id),
    constraint rating_range check (rating between 1 and 5)
);